---
- name: Install Docker
  hosts: all
  become: yes
  tasks:
    - name: Install required system packages
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg

    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker apt repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    # - name: Install Docker Engine specific version
    #   apt:
    #     name: "{{ item }}"
    #     state: present
    #   loop:
    #     - docker-ce=5:24.0.9-1
    #     - docker-ce-cli=5:24.0.9
    #     - containerd.io=1.6.8-1

    - name: Install Docker Engine specific version
      apt:
        name:
          - docker-ce=5:24.0.9-1~ubuntu.22.04~jammy
          - docker-ce-cli=5:24.0.9-1~ubuntu.22.04~jammy
          - containerd.io
        state: present


    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

- name: Install Docker
  hosts: localhost
  become: yes
  tasks:
    - name: Install required system packages
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg

    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker apt repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Install Docker Engine
      apt:
        name: docker-ce
        state: latest
        update_cache: yes

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes


- name: Add user to the Docker group
  hosts: all
  become: yes
  tasks:
    - name: Add rke user to docker group
      user:
        name: rke
        groups: docker
        append: yes

